#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update

  brew bundle check 2>&1 >/dev/null || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if ! command -v elixir >/dev/null 2>&1; then
  echo "==> Installing erlang and elixir…"
  asdf install
fi

if [ -f "mix.exs" ]; then
  echo "==> Installing mix dependencies…"
  mix deps.get
fi
