#!/bin/sh

# script/build: Build and install the escript.

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

script/test

export MIX_ENV="prod"

echo "==> Build and install escript…"

mix escript.install --force
