#!/bin/sh

# script/bump: Increments the version by major|minor|patch, creates a release commit, creates a
#              release tag, and pushes to the remote repo

set -e
cd "$(dirname "$0")/.."

script/test
script/docs

mix version.inc $1
version_text=v$(mix version.current)
sed -E -i .backup "s/^mix escript.install (.*) v([0-9]+\.[0-9]+\.[0-9]+)/mix escript.install \1 $version_text/" README.md
git commit -am "Release $version_text"
git tag "$version_text"
git push --tags origin master
